#!/usr/bin/python3
from sys import argv

def factorize(num):
    """ Factorizes a number into two smaller numbers """
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return num // i, i
    return num, 1

def main():
    with open(argv[1], "r") as f:
        for line in f:
            n = int(line.strip())
            p, q = factorize(n)
            print("{}={}*{}".format(n, p, q))

if __name__ == "__main__":
    main()
