#!/usr/bin/python3
from sys import argv
from math import sqrt

input_file = open(argv[1])
num = int(input_file.readlines()[0])

def is_prime(n):
    """Check if the input number is prime

    Args:
        n (int): number to be checked
    """
    if n <= 2 or n in (3, 5, 7):
        return True
    if int(list(str(n))[-1]) in (2, 4, 5, 6, 8, 0):
        return False
    for i in range(3, int(sqrt(n)) + 1):
        if (n % i == 0):
            return False
    return True

def check(f_list):
    """Checks if the two prime factors are found and if so exits the program

    Args:
        f_list (list): list of prime factors of the input number
    """
    for x in f_list:
        for y in f_list:
            if (x * y == num):
                print("{}={}*{}".format(num, int(x), int(y)))
                exit()

factor_list = []
for i in range(2, int(num / 2) + 1):
    if (num % i == 0):
        if is_prime(i):
            factor_list.append(i)

check(factor_list)
